### ISSUE TITLE
s3fs not using credential_process in ~/.aws/config

### ISSUE THREAD

**Issue by akrish2011** [s3fs-fuse/s3fs-fuse#1724] opened 2021-07-20 19:20 UTC
s3fs is not able to use credential_process in ~/.aws/config, I am not finding any option to force use S3FS to use ~/.aws/config like aws cli to generate STS tokens using credential_process defined in the config file. This will help to solve token expiry problem in S3FS as well as solve the problem of remounting each time after token expiry

**Comment by gaul** [comment] 2021-07-25 03:15
Duplicate of #1122.

**Closed by gaul** 2021-07-25 03:15 UTC
