### ISSUE TITLE
How to fix permanently transport end point is not connected in S3fs

### ISSUE THREAD

**Issue by mitosistech** [s3fs-fuse/s3fs-fuse#152] opened 2015-03-16 06:12 UTC
I have one s3 bucket and two EC2 instance.I have mounted S3 bucket in EC2 instance.We are acessing all file of S3 bucket through our App.Now a days "Tansport end point is not connected" to s3fs is coming frequently.For fix this issue I am unmounting and mount again s3 bucket in EC2 instance.But I need the root cause of this issue.Why its coming frequently.Please help me.

**Comment by Stony2k** [comment] 2015-03-17 09:13
I have the same problem its killing my mount point. Is there a solution?

**Comment by mitosistech** [comment] 2015-03-17 10:20
I have used s3fs 1.74

**Comment by Stony2k** [comment] 2015-03-17 10:22
ok :( i have used the newest version 1.78.. hmm

**Comment by mitosistech** [comment] 2015-03-17 10:34
For you also same Tranport endpoint is not connected error

**Comment by Stony2k** [comment] 2015-03-17 10:35
Yes same problem

**Comment by mitosistech** [comment] 2015-03-17 10:38
If will do un mount and again mount then  it will work.But this is not permanent fix.If many times this same problem will come ,it is not good.So I am searching permanent solution.I think this is not version problem.

**Comment by boazrf** [comment] 2015-03-18 09:52
Some observations:

1. Seems like that problem is less frequent when using full debug + foreground mode (-d -f  -o curldbg -o f2). Might be due to some tiny delays caused by writing out the debug messages.

2. From https://code.google.com/p/s3fs/issues/detail?id=426: it looks like it can be related to multireq_max param. Default is 20 but it is recommended to try smaller number (i.e. multireq_max=5).

In any case - this is indeed an annoying issue that needs attention.

**Comment by mitosistech** [comment] 2015-03-18 13:03
Can you please tell me ,where this multireq_max param is present?

**Comment by Stony2k** [comment] 2015-03-18 13:52
I think your can set that parameter in your fstab file i have test it now 

use allow_other,multireq_max=5  0 0

I don't know if its correct but its working.

**Comment by mitosistech** [comment] 2015-03-18 14:53
But I have set use user allow_other in fuse.conf

**Comment by boazrf** [comment] 2015-03-18 17:41
I'm setting it when running s3fs from command line:
/usr/local/bin/s3fs [bucket] [mount-point] -o multireq_max=5

**Comment by mitosistech** [comment] 2015-03-19 06:00
I have used this command 
$ sudo s3fs your_backet_name -o use_cache=/tmp -o allow_other /mnt/s3storage


you are telling ,I will give command like this

$ sudo s3fs your_backet_name -o use_cache=/tmp -o allow_other -o multireq_max=5 /mnt/s3storage

Am I right?  

Have you know , how one S3 bucket will work for mount local folder of two EC2 instance?

**Comment by darrencruse** [comment] 2015-03-19 20:01
Just fwiw we've been migrating a bunch of php content from some old apache servers to amazon s3 w/s3fs and I'd had this problem 2 or 3 times in the last few months.

But we changed our configurations to about double our load of requests on tuesday and this problem has went to happening about 2 or 3 times now *per day*.

Glad to see the suggestion about multireq_max am getting ready to try it.

Does anybody know though - if multireq_max refers to the number of simultaneous requests to amazon S3, and the default is 20 but we reduce it to 5...

Will this hurt performance?  i.e. response times?

**Comment by darrencruse** [comment] 2015-04-01 22:58
I just finished putting a watchdog on this mount point that we keep losing - thought I'd share it in case it helps others here.

I used this blog as a guide it was helpful:
http://blog.eracc.com/2010/05/08/linux-monitor-a-service-with-a-watchdog-script/

Here's my script I put in root's crontab:

#!/bin/bash
#
# s3fs-watchdog.sh
#
# Run from the root user's crontab to keep an eye on s3fs which should always
# be mounted.
#
# Note:  If getting the amazon S3 credentials from environment variables
#   these must be entered in the actual crontab file (otherwise use one
#   of the s3fs other ways of getting credentials).
#
# Example:  To run it once every minute getting credentials from envrironment
# variables enter this via "sudo crontab -e":
#
#   AWSACCESSKEYID=XXXXXXXXXXXXXX
#   AWSSECRETACCESSKEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#   * * * * * /root/s3fs-watchdog.sh
#

NAME=s3fs
BUCKET=<yourbucket>
MOUNTPATH=<yourmountpath>
MOUNT=/bin/mount
UMOUNT=/bin/umount
NOTIFY=<whotoemail>
NOTIFYCC=<whoelsetoemail>
GREP=/bin/grep
PS=/bin/ps
NOP=/bin/true
DATE=/bin/date
MAIL=/bin/mail
RM=/bin/rm

$PS -ef|$GREP -v grep|$GREP $NAME|grep $BUCKET >/dev/null 2>&1
case "$?" in
   0)
   # It is running in this case so we do nothing.
   $NOP
   ;;
   1)
   echo "$NAME is NOT RUNNING for bucket $BUCKET. Remounting $BUCKET with $NAME and sending notices."
   $UMOUNT $MOUNTPATH >/dev/null 2>&1
   $MOUNT $MOUNTPATH >/tmp/watchdogmount.out 2>&1
   NOTICE=/tmp/watchdog.txt
   echo "$NAME for $BUCKET was not running and was started on `$DATE`" > $NOTICE
   $MAIL -n -s "$BUCKET $NAME mount point lost and remounted" -c $NOTIFYCC $NOTIFY < $NOTICE
   $RM -f $NOTICE
   ;;
esac

exit

**Comment by dev-yohan** [comment] 2015-04-07 14:37
seems to work fine @darrencruse, thanks for the script!

**Comment by ggtakec** [comment] 2015-04-12 02:31
#167 may have solved this Issue.
If this issue reason is timeout for connecting/reading/writing, the default value changing maybe solve this.
If you got same error with latest codes, please try to set connect_timeout and readwrite_timeout options.
Thanks in advance for your help.

**Comment by chrisschaub** [comment] 2015-04-14 21:14
I'm using the latest master and can get the connect to work by specifying keys directly. But, using -o iam_role=somerole does not work, always get Transport endpoint is not connected. Does the iam_role stuff work?

**Comment by ggtakec** [comment] 2015-04-18 13:08
@chrisschaub I think "iam_role" option is working without problem.
Probably you should do that this option needs "role name" parameter please check name and your role setting on console.
Thanks in advance for your help.

**Comment by jackyq2015** [comment] 2015-08-20 14:34
Thanks for the watchdog script. It's great!

Looking forward a fix in the code base though.

**Comment by Fei-Guang** [comment] 2016-06-02 08:56
this issue opened today and the version is ossfs_1.79.8_ubuntu14.04_amd64

**Comment by stefandelaet** [comment] 2017-01-12 11:55
I have the same  issue using s3fs version 1.80 , using centos 7 on an ec2 instance

**Comment by ggtakec** [comment] 2017-01-15 09:47
@stefandelaet 
Please try to specify readwrite_timeout(and connect_timeout) option, the result maybe help us to solve this issue.
And if you can, please use latest version in master branch(like #506)

Thanks in advance for your help.

**Comment by mgla** [comment] 2017-02-10 09:17
I am experiencing this issue with s3fs v1.180 (commit_d40da2c). 
Mount options: _netdev,allow_other,iam_role=auto,umask=0000

readwrite_timeout is 60 seconds (default, although the Readme.md states 30 is the default).
connect_timeout is 300 seconds (default).

I found a rather old pull request (https://github.com/s3fs-fuse/s3fs-fuse/pull/167), which seemingly tried to address this issue, but I suppose it did not work.

Is there anything I can do to assist with this issue?

**Comment by davidfischer-ch** [comment] 2017-05-03 12:04
Hello, I implemented a watcher that try to read a file inside the s3fs "directory" to detect any disconnection and then remount the target. This check is made by default every second. Since then, I never encountered the issue. I though it was worth sharing my experience.

**Comment by ClemensSchneider** [comment] 2017-07-11 08:40
Is there any logfile we could check to give a hint for the reason of the sudden disconnects?

**Comment by b0ku1** [comment] 2017-08-05 09:29
Did anyone get to the bottom of this? Thanks.

**Comment by etwillbefine** [comment] 2017-08-10 08:42
For us it was a memory issue. I enabled debug using `-d`, found this in the syslog (not in messages log file as documented): 
```
kernel: [61022.091965] Out of memory: Kill process 2441 (s3fs) score 569 or sacrifice child
kernel: [61022.095825] Killed process 2441 (s3fs) total-vm:1292244kB, anon-rss:593880kB, file-rss:0kB
```

Trying now to solve it following [this comment](https://github.com/s3fs-fuse/s3fs-fuse/issues/340#issuecomment-195930065). Will update this post when it seems to be solved. 
We are not interested in high performance / caching anyway for our use case. If you are, you might want to follow a different approach.

**Comment by ggtakec** [comment] 2019-03-30 06:31
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.

**Closed by ggtakec** 2019-03-30 06:31 UTC

**Comment by TheRealAnubis** [comment] 2019-04-22 13:46
Sorry for the thread necromancy, but for me the issue seemed to be caused by `updatedb` daemon triggering the OOM killer on S3FS. Adding my S3 mountpoint to the `PRUNEPATHS` section of `updatedb.conf` seemed to resolve the issue.

**Comment by ggtakec** [comment] 2019-04-22 15:02
@TheRealAnubis The same point was mentioned in https://github.com/s3fs-fuse/s3fs-fuse/issues/417#issuecomment-291850522 .
We need to be careful about updatedb.
Thanks for your kindness.

@gaul We should describe this in the wiki.
I tried to add [FAQ in WIKI](https://github.com/s3fs-fuse/s3fs-fuse/wiki/FAQ#q-becomes-unstable-using-updatedbkicked-oom-killer)
Please let me know if there is a problem.

**Comment by vcombey** [comment] 2021-01-03 15:55
I got random disconnects using: https://github.com/efrecon/docker-s3fs-client/.
I'm using version 1.86.

issue link: https://github.com/efrecon/docker-s3fs-client/issues/8

**Comment by rohit-the-coder** [comment] 2021-02-05 11:27
I am facing this issue too.  Has anybody found the permanent solution to it?

**Comment by gaul** [comment] 2021-04-21 14:33
Please test with the latest version 1.89 and open a new issue if symptoms persist.

**Comment by aarcro** [comment] 2021-05-09 04:32
I just hit it on 1.89. large -4.5 TB and growing wasabi bucket. unmount/mount only recovered it briefly (minute or two). I removed use_cache and it is no longer disconnecting (but using more bandwidth). Prior to the first instance of the failure I'd hit 98% disk use, and removed some older files from the use_cache dir.

**Comment by devopseze** [comment] 2021-05-13 15:43
Hi aarcro, please can you elaborate more on you solution.

**Comment by aarcro** [comment] 2021-05-13 19:33
> Hi aarcro, please can you elaborate more on you solution.

Ultimate solution was to switch to goofys

**Comment by devopseze** [comment] 2021-05-17 16:03
Thanks Aarcro, I have started  looking into goofys to see how I can leverage on it.  Currently  using s3fs to mount a path to an s3 bucket for  dataflow application. the s3fs crash had been persistent. (cannot access data: Transport endpoint is not connected).  are you on Linkedln

**Comment by wcheek** [comment] 2025-04-09 04:18
I've been seeing the same random disconnects (after ~1 month) using [`mount-s3`](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mountpoint.html). Getting my inspiration from @darrencruse [above](https://github.com/s3fs-fuse/s3fs-fuse/issues/152), I made a [working script solution for mount-s3](https://gist.github.com/wcheek/c1a1347b660775866e70629bee6b29cc).
