### ISSUE TITLE
whats the  limit on the size of file can be written to s3fs?

### ISSUE THREAD

**Issue by Fei-Guang** [s3fs-fuse/s3fs-fuse#508] opened 2016-11-23 03:36 UTC
it's ok to write a normal size file ,but the process will 

terminate when a large file like 10GB is writing to s3fs,

whats the  limit on the size of file can be written to s3fs?

**Comment by andrewgaul** [comment] 2016-11-24 02:20
Can you share the step to reproduce your symptom?  I successfully wrote 10 GB via:

```
$ dd if=/dev/zero of=$MOUNTPOINT/out bs=10M count=1000
1000+0 records in
1000+0 records out
10485760000 bytes (10 GB) copied, 334.098 s, 31.4 MB/s
```

**Comment by Fei-Guang** [comment] 2016-11-24 03:08
have you added the option  conv=fdatasync to your writing? and tried multiple processes to write at same time?.
we are in a multi-user environment, there are many processes to write to a same mount point and it 's dead

**Comment by andrewgaul** [comment] 2016-11-24 05:30
It will help if you can give the steps to reproduce these symptoms.  Otherwise we are stabbing in the dark.

**Comment by ggtakec** [comment] 2017-01-07 08:52
@Fei-Guang I'm sorry for my late reply
Could you put log by s3fs? or do you have any log at s3fs exiting?
And plese let me know about s3fs version(s3fs --version).

I fixed a bug about uploading by #511 last month.
If you can, please try to use latest codes in master branch.

Thanks in advance for your assistance.

**Comment by nycdubliner** [comment] 2017-03-12 19:33
I think I'm having the same issue.

Normal usage for most files works really well. Large files copy finish with a zero length file.
(Sometimes this happens immediately after the data is copied, sometimes the fuse mount hangs for 10-12 minutes before becoming interactive again and returning a 0 lenght file.)


**To reproduce:**
I ran s3fs as follows:
`s3fs -o allow_other -o umask=0002 cloud-nas-1 cloud-nas/ -f -odbglevel=info | tee s3fs-log
`
Log data attached in file s3fs-log.txt
[s3fs-log.txt](https://github.com/s3fs-fuse/s3fs-fuse/files/836839/s3fs-log.txt)

**From another terminal:**

```
pi@raspberrypi:~ $ time dd if=/dev/zero of=cloud-nas/out bs=10M count=170

dd: closing output file ‘cloud-nas/out’: Operation not supported

pi@raspberrypi:~ $ ls -lah cloud-nas/out 

-rwxrwxr-x 1 pi pi 0 Mar 12 19:10 cloud-nas/out

```

**Details:**
My setup is a Rasperry Pi 3 running current raspbian and current s3fs (1.8)

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
pi@raspberrypi:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

pi@raspberrypi:~ $ dpkg -l | grep -i fuse
ii  fuse                                  2.9.3-15+deb8u2                           armhf        Filesystem in Userspace
ii  gvfs-fuse                             1.22.2-1                                  armhf        userspace virtual filesystem - fuse server
ii  libconfuse-common                     2.7-5                                     all          Common files for libConfuse
ii  libconfuse0:armhf                     2.7-5                                     armhf        Library for parsing configuration files
ii  libfuse-dev                           2.9.3-15+deb8u2                           armhf        Filesystem in Userspace (development)
ii  libfuse2:armhf                        2.9.3-15+deb8u2                           armhf        Filesystem in Userspace (library)
ii  ntfs-3g                               1:2014.2.15AR.2-1+deb8u3                  armhf        read/write NTFS driver for FUSE

pi@raspberrypi:~ $ s3fs --version
Amazon Simple Storage Service File System V1.80(commit:6affeff) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

Thanks for your work on this project, it's working well for me with the exception of this case. 
If you need any other debug information, please ask.

T.

**Comment by ggtakec** [comment] 2017-04-09 07:31
@nycdubliner Thanks for your report.

I could not find the reason fo this problem in your log, it was a log until just before the operation when probably creating the "/out" file for the first time(0 bytes).
If you can, please try to run s3fs with "-o curldbg" again.

And if timeout is the cause of this problem, please also try options such as connect_timeout/readwrite_timeout/retries.

Regards,

**Comment by ggtakec** [comment] 2019-03-30 08:37
We kept this issue open for a long time.
Is this problem continuing?
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.

If you encounter problems with s3fs as well, try using the `dbglevel`` -d` `curldbg` or similar option to print out the log.
It contains information for the solution.

**Closed by ggtakec** 2019-03-30 08:37 UTC
