### ISSUE TITLE
Can't install - package requirements

### ISSUE THREAD

**Issue by jacobischwartz** [s3fs-fuse/s3fs-fuse#2] opened 2013-12-25 04:40 UTC
Hi,

I've installed s3fs before on other Ubuntu systems but this time I'm running into issues. This is also the first time I'm using a Bitnami Ubuntu stack so it's completely possible that's related. Here's my install attempt:

```
$ sudo ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for pkg-config... /opt/bitnami/common/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for DEPS... no
configure: error: Package requirements (fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6 libcrypto >= 0.9) were not met:

No package 'fuse' found
No package 'libcurl' found
No package 'libxml-2.0' found
No package 'libcrypto' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEPS_CFLAGS
and DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

The interesting thing is that the packages listed ARE installed and DO meet the version requirements:

```
$ pkg-config --list-all
iso-codes        iso-codes - ISO country, language, script and currency codes and translations
libtasn1         libtasn1 - Library for ASN.1 and DER manipulation
gnutls           GnuTLS - Transport Security Layer implementation for the GNU system
p11-kit-1        p11-kit - Library and proxy module for properly loading and sharing PKCS
libsepol         libsepol - SELinux policy library
openssl          OpenSSL - Secure Sockets Layer and cryptography libraries and tools
xkeyboard-config XKeyboardConfig - X Keyboard configuration data
librtmp          librtmp - RTMP implementation
libselinux       libselinux - SELinux utility library
fuse             fuse - Filesystem in Userspace
libcrypto        OpenSSL-libcrypto - OpenSSL cryptography library
zlib             zlib - zlib compression library
libxml-2.0       libXML - libXML library version2.
com_err          com_err - Common error description library
udev             udev - udev
usbutils         usbutils - USB device database
libidn           Libidn - IETF stringprep, nameprep, punycode, IDNA text processing.
libcurl          libcurl - Library to transfer files with ftp, http, etc.
gnutls-extra     GnuTLS-extra - Additional add-ons for GnuTLS licensed under GPL
dbus-python      dbus-python - Python bindings for D-Bus
libssl           OpenSSL - Secure Sockets Layer and cryptography libraries
```

Obviously pkg-config can see those packages so I'm not sure why the installer can't. Any ideas what's going on? 

Cheers,

Jacob

**Comment by intelliant01** [comment] 2015-08-12 14:55
Am on an Ubuntu 12.04 LTS Bitnami Magento stack, hence am posting it herein as it seems a quiet similar problem.

Have been trying to install s3fs latest release available herein.

Will a lot of struggle managed to get some of the package dependencies resolved. However, have not succeeded completely. Hence am here seeking help before giving up.

```
root@test-server:/usr/src/s3fs-fuse-master# ./autogen.sh
root@test-server:/usr/src/s3fs-fuse-master# ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking s3fs build with nettle(GnuTLS)... no
checking s3fs build with OpenSSL... no
checking s3fs build with GnuTLS... no
checking s3fs build with NSS... no
checking for pkg-config... /opt/bitnami/common/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for common_lib_checking... yes
checking compile s3fs with... OpenSSL
checking for DEPS... yes
checking for malloc_trim... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating test/Makefile
config.status: creating doc/Makefile
config.status: executing depfiles commands
root@ip-10-121-65-218:/usr/src/s3fs-fuse-master# make
Making all in src
make[1]: Entering directory `/usr/src/s3fs-fuse-master/src'
g++ -DPACKAGE_NAME=\"s3fs\" -DPACKAGE_TARNAME=\"s3fs\" -DPACKAGE_VERSION=\"1.79\" -DPACKAGE_STRING=\"s3fs\ 1.79\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"s3fs\" -DVERSION=\"1.79\" -DHAVE_MALLOC_TRIM=1 -I.  -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/opt/bitnami/common/include -I/opt/bitnami/common/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT s3fs.o -MD -MP -MF .deps/s3fs.Tpo -c -o s3fs.o s3fs.cpp
mv -f .deps/s3fs.Tpo .deps/s3fs.Po
g++ -DPACKAGE_NAME=\"s3fs\" -DPACKAGE_TARNAME=\"s3fs\" -DPACKAGE_VERSION=\"1.79\" -DPACKAGE_STRING=\"s3fs\ 1.79\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"s3fs\" -DVERSION=\"1.79\" -DHAVE_MALLOC_TRIM=1 -I.  -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/opt/bitnami/common/include -I/opt/bitnami/common/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT curl.o -MD -MP -MF .deps/curl.Tpo -c -o curl.o curl.cpp
mv -f .deps/curl.Tpo .deps/curl.Po
g++ -DPACKAGE_NAME=\"s3fs\" -DPACKAGE_TARNAME=\"s3fs\" -DPACKAGE_VERSION=\"1.79\" -DPACKAGE_STRING=\"s3fs\ 1.79\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"s3fs\" -DVERSION=\"1.79\" -DHAVE_MALLOC_TRIM=1 -I.  -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/opt/bitnami/common/include -I/opt/bitnami/common/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT cache.o -MD -MP -MF .deps/cache.Tpo -c -o cache.o cache.cpp
mv -f .deps/cache.Tpo .deps/cache.Po
g++ -DPACKAGE_NAME=\"s3fs\" -DPACKAGE_TARNAME=\"s3fs\" -DPACKAGE_VERSION=\"1.79\" -DPACKAGE_STRING=\"s3fs\ 1.79\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"s3fs\" -DVERSION=\"1.79\" -DHAVE_MALLOC_TRIM=1 -I.  -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/opt/bitnami/common/include -I/opt/bitnami/common/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT string_util.o -MD -MP -MF .deps/string_util.Tpo -c -o string_util.o string_util.cpp
mv -f .deps/string_util.Tpo .deps/string_util.Po
g++ -DPACKAGE_NAME=\"s3fs\" -DPACKAGE_TARNAME=\"s3fs\" -DPACKAGE_VERSION=\"1.79\" -DPACKAGE_STRING=\"s3fs\ 1.79\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"s3fs\" -DVERSION=\"1.79\" -DHAVE_MALLOC_TRIM=1 -I.  -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/opt/bitnami/common/include -I/opt/bitnami/common/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT s3fs_util.o -MD -MP -MF .deps/s3fs_util.Tpo -c -o s3fs_util.o s3fs_util.cpp
mv -f .deps/s3fs_util.Tpo .deps/s3fs_util.Po
g++ -DPACKAGE_NAME=\"s3fs\" -DPACKAGE_TARNAME=\"s3fs\" -DPACKAGE_VERSION=\"1.79\" -DPACKAGE_STRING=\"s3fs\ 1.79\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"s3fs\" -DVERSION=\"1.79\" -DHAVE_MALLOC_TRIM=1 -I.  -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/opt/bitnami/common/include -I/opt/bitnami/common/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT fdcache.o -MD -MP -MF .deps/fdcache.Tpo -c -o fdcache.o fdcache.cpp
mv -f .deps/fdcache.Tpo .deps/fdcache.Po
g++ -DPACKAGE_NAME=\"s3fs\" -DPACKAGE_TARNAME=\"s3fs\" -DPACKAGE_VERSION=\"1.79\" -DPACKAGE_STRING=\"s3fs\ 1.79\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"s3fs\" -DVERSION=\"1.79\" -DHAVE_MALLOC_TRIM=1 -I.  -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/opt/bitnami/common/include -I/opt/bitnami/common/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT common_auth.o -MD -MP -MF .deps/common_auth.Tpo -c -o common_auth.o common_auth.cpp
mv -f .deps/common_auth.Tpo .deps/common_auth.Po
g++ -DPACKAGE_NAME=\"s3fs\" -DPACKAGE_TARNAME=\"s3fs\" -DPACKAGE_VERSION=\"1.79\" -DPACKAGE_STRING=\"s3fs\ 1.79\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"s3fs\" -DVERSION=\"1.79\" -DHAVE_MALLOC_TRIM=1 -I.  -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/opt/bitnami/common/include -I/opt/bitnami/common/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT openssl_auth.o -MD -MP -MF .deps/openssl_auth.Tpo -c -o openssl_auth.o openssl_auth.cpp
mv -f .deps/openssl_auth.Tpo .deps/openssl_auth.Po
g++  -g -O2 -Wall -D_FILE_OFFSET_BITS=64   -o s3fs s3fs.o curl.o cache.o string_util.o s3fs_util.o fdcache.o common_auth.o openssl_auth.o   -pthread -L/usr/local/lib -L/opt/bitnami/common/lib -lfuse -lcurl -lxml2 -lcrypto
/lib/x86_64-linux-gnu/libssl.so.1.0.0: undefined reference to `CRYPTO_memcmp@OPENSSL_1.0.0'
/opt/bitnami/common/lib/libcurl.so: undefined reference to `SSLv2_client_method@OPENSSL_1.0.0'
/opt/bitnami/common/lib/libxml2.so: undefined reference to `gzopen64@ZLIB_1.2.3.3'
collect2: ld returned 1 exit status
make[1]: *** [s3fs] Error 1
make[1]: Leaving directory `/usr/src/s3fs-fuse-master/src'
make: *** [all-recursive] Error 1
```

Had to adjust the PKG_CONFIG_PATH to ensure all library modules were being picked up -
```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/bitnami/common/lib/pkgconfig/:/usr/lib/x86_64-linux-gnu/pkgconfig/
```

as I found several non-standard module installations -
```
root@test-server:/usr/src/s3fs-fuse-master# locate .pc
/lib/modules/3.2.0-61-virtual/modules.pcimap
/opt/bitnami/common/lib/pkgconfig/apr-1.pc
/opt/bitnami/common/lib/pkgconfig/apr-util-1.pc
/opt/bitnami/common/lib/pkgconfig/freetype2.pc
/opt/bitnami/common/lib/pkgconfig/icu-i18n.pc
/opt/bitnami/common/lib/pkgconfig/icu-io.pc
/opt/bitnami/common/lib/pkgconfig/icu-le.pc
/opt/bitnami/common/lib/pkgconfig/icu-lx.pc
/opt/bitnami/common/lib/pkgconfig/icu-uc.pc
/opt/bitnami/common/lib/pkgconfig/libcrypto.pc
/opt/bitnami/common/lib/pkgconfig/libcurl.pc
/opt/bitnami/common/lib/pkgconfig/libexslt.pc
/opt/bitnami/common/lib/pkgconfig/libpcre.pc
/opt/bitnami/common/lib/pkgconfig/libpcreposix.pc
/opt/bitnami/common/lib/pkgconfig/libpng.pc
/opt/bitnami/common/lib/pkgconfig/libpng15.pc
/opt/bitnami/common/lib/pkgconfig/libssl.pc
/opt/bitnami/common/lib/pkgconfig/libtiff-4.pc
/opt/bitnami/common/lib/pkgconfig/libxml-2.0.pc
/opt/bitnami/common/lib/pkgconfig/libxslt.pc
/opt/bitnami/common/lib/pkgconfig/openssl.pc
/opt/bitnami/common/lib/pkgconfig/tcnative-1.pc
/opt/bitnami/common/lib/pkgconfig/yaml-0.1.pc
/opt/bitnami/common/lib/pkgconfig/zlib.pc
/opt/bitnami/sqlite/lib/pkgconfig/sqlite3.pc
/opt/bitnami/varnish/lib/pkgconfig/varnishapi.pc
/usr/lib/pkgconfig/dbus-python.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/com_err.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gnutls-extra.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gnutls.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libcrypto.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libcurl.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libidn.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/librtmp.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libssl.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libtasn1.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libxml-2.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/openssl.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/p11-kit-1.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/zlib.pc
/usr/local/lib/pkgconfig/fuse.pc
/usr/share/pkgconfig/iso-codes.pc
/usr/share/pkgconfig/udev.pc
/usr/share/pkgconfig/usbutils.pc
/usr/share/pkgconfig/xkeyboard-config.pc
/usr/src/fuse-2.9.4/fuse.pc
/usr/src/fuse-2.9.4/fuse.pc.in
```

Am not sure if the problem is more due to the bitnami way of organising stuff or plain ubuntu problem.

Any guidance in this regard will be much appreciated. 

The alternate solution seems to be to upgrade the bitnami stack to 14.04 Ubuntu, which is something I would like to avoid for another month or so at least.

**Comment by kahing** [comment] 2015-08-12 19:55
my guess is that it's picking up libcurl from /opt but that's incompatible with your libssl in /lib.

**Comment by intelliant01** [comment] 2015-08-13 11:28
@kahing You were spot on -

Modified 
```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/bitnami/common/lib/pkgconfig/:/usr/lib/x86_64-linux-gnu/pkgconfig/
```
to
```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig/
```
and it is all working perfectly fine.

**Comment by ggtakec** [comment] 2016-01-17 06:15
I closed this issue, but if you have more problem, pleae post new issue.
Thanks in advance for your help.

**Closed by ggtakec** 2016-01-17 06:15 UTC
