### ISSUE TITLE
mirror files clean

### ISSUE THREAD

**Issue by 815331793** [s3fs-fuse/s3fs-fuse#823] opened 2018-09-20 04:01 UTC
If a user kill the s3fs process while read or write a large file ( mount with use_cache option）.Then the next mount  with  'del_cache' option will not clean the files in hidden folder .bucket.mirror folder. Can we add the code to clean the hidden colder when use the del_cache option

**Comment by gaul** [comment] 2019-03-15 08:11
Duplicate of #827?  @815331793 does a93e500b44a5d43a5183f997cb9b8d347ce258d6 resolve this issue?

**Comment by gaul** [comment] 2019-04-09 09:46
Closing due to inactivity.

**Closed by gaul** 2019-04-09 09:46 UTC
