### ISSUE TITLE
Deadlock for FdManager::fd_manager_lock && FdEntity::fdent_lock when write data concurrently

### ISSUE THREAD

**Issue by Roay** [s3fs-fuse/s3fs-fuse#2438] opened 2024-03-27 09:42 UTC
s3fs version :  master

**The First :**
s3fs_write  ->  'autoent.GetExistFdEntity'  ->  'FdManager::get()->GetExistFdEntity'
     first lock:  FdManager::fd_manager_lock [line: 659  in fdcache.cpp]
     sec lock:  FdEntity::fdent_lock [line: 361  in fdcache_entity.cpp]
**The Second :**
s3fs_write  ->  'ent->Write()'  ->  'WriteMixMultipart()'  ->  'NoCacheLoadAndPost'  ->  'ChangeEntityToTempPath'
     first lock:  FdEntity::fdent_lock [line: 2088  in fdcache_entity.cpp]
     sec lock:  FdManager::fd_manager_lock [line: 780  in fdcache.cpp]

**Comment by Roay** [comment] 2024-03-27 09:44
Triggered when there is not enough disk space

**Comment by amarjayr** [comment] 2024-06-10 16:38
@gaul apologies for the direct ping but any updates here? I've included a python script to reproduce the deadlock in #2463 (which I closed as duplicate). 

I'm happy to submit a fix, but could use some guidance on the recommended solution.

**Comment by ggtakec** [comment] 2024-06-23 10:46
@Roay 
Thank you for your detailed explanation.
@amarjayr 
And also for providing the code for testing, thanks!

I checked the calling sequence you pointed out and confirmed the possibility of a deadlock.
It seems that a lot of checking is required to fix it, so please wait a little while. (Because there is an issue with the logic)

**Comment by ggtakec** [comment] 2024-06-23 17:13
@Roay @amarjayr 
I have posted PR #2478 as a solution to this problem.
If you can test the problem with the source code, please try it.
Thanks in advance for your assistance.

**Comment by amarjayr** [comment] 2024-06-24 21:57
@ggtakec this fixes the repro provided in #2463. 

Thanks for the quick turnaround!

**Comment by ggtakec** [comment] 2024-06-25 14:18
@amarjayr Thank you for your cooperation, letting us know that the issue has been resolved.
We expect the PR will be merged after review, please wait a little while until then.

**Comment by ggtakec** [comment] 2024-07-01 13:31
#2478 was merged, I closed this.
Thanks.

**Closed by ggtakec** 2024-07-01 13:31 UTC
