### ISSUE TITLE
Getting Double PUTs when writing files

### ISSUE THREAD

**Issue by barryhunter** [s3fs-fuse/s3fs-fuse#427] opened 2016-06-02 10:11 UTC
Since using s3fs, noticed we getting a high cost on 

> $0.0125 per GB-Month prorated for small objects deleted or overwritten before 30 days in Standard-Infrequent Access

However we don't delete anything, only writing at this time!

Enabled the S3 logs, and noticed an apparent double put. 

Captured log, for writing one single file!
http://data.geograph.org.uk/amazon-log-example.txt
Note the logs only have one second granulity, so the log entries are almost certainly out of order, had to sort the list to combine from multiple distinct amazon provided log files. 

It seems there is a 0-byte PUT, and then final 106490 byte PUT. (I'm guessing that was order anyway, because tehre is a 106490 file in S3) 

The file is copied with the python shutil.copyfile function. Did use copy2 originally, but that resulted many PUTs (s3fs would write the file, then the chown/touch ext would result in two COPY operations) I just can't figure out how to eliminate this last double write. 

(the large number of 404 requests before writing, hoping enable_noobj_cache will help with. although would like to turn off checking for all the 'compatibility' folder types, dont need them, they wont exist. But thats seperate issue!)

**Comment by ggtakec** [comment] 2016-06-12 01:42
@barryhunter

You are correct, s3fs puts a object twice when it creates file on S3.
It is associated with FUSE.
Operation of the copy command, first create a file first, then writing of data using the file handle.
When s3fs creates the file, PUTs 0 byte file to S3.
In a future version, it may be able to change this behavior, but it is still undecided.

Regards,

**Comment by patroy** [comment] 2016-09-05 18:20
This is also a problem when you use S3 event notifications. It creates two SNS, Lambda or SNS requests.

**Comment by gabpaladino** [comment] 2016-09-30 17:59
Hi, i'm using with Lambda and have to pay twice :(
There are some workaround to filter event with object `"size": 0` from trigger Lambda?
Regards.

**Comment by patroy** [comment] 2016-09-30 18:02
I do it in the lambda code:

if (event.Records[0].s3.object.size > 0) ... 

But you will still get charged for those. I just do this to prevent the rest of my code from running twice.

**Comment by gabpaladino** [comment] 2016-09-30 18:14
yes @patroy i'm coding it too, it would be nice if possible a filter as prefix and suffix

**Comment by derekmurawsky** [comment] 2017-03-24 17:25
+1 this is really bad/unexpected behavior. I, too, run lambdas based on files created in s3, and this can cause a lot of issues. I will implement the workaround in my lambda as suggested by @patroy, but this really shouldn't be the behavior. At the very least, can we get an option to disable this behavior?

**Comment by kahing** [comment] 2017-03-29 22:44
part of the reason for double PUT is the strong POSIX compatibility offered by s3fs. If you don't need that much POSIX, there are other tools that will use fewer S3 requests.

**Comment by MrMitch17** [comment] 2017-04-17 21:49
I am running into this issue twice also. Where a single file upload is causing my lambda code to trigger twice.  I can code around it.  But it I figured I'd make a note that I am experiencing it also.

**Comment by stephanechauvin** [comment] 2017-12-18 16:57
I encounter an odd behavior over the double PUT : for files that are bigger than 26MB, I also have the first PUT event (with the 0 size), but never the second, although it works nicely for files under 25 MB (first 0 size PUT event then the "regular" final PUT event).

Nevertheless, the files are correctly copied into the S3 bucket, regardless of their size. It's just the event that is missing for "big files".

Sorry to pollute this issue with my strange behavior. Tell me if I should open another issue for this.
Thanks

BTW, I use s3fs v 1.80. Everything else works well.

**Comment by kollyma** [comment] 2018-12-13 10:31
@ggtakec: Thanks for the details
We run into this issue with WORM Buckets (Write-Once-Read-Many).
Any plans to integrate an option for "less POSIX compliance but WORM Bucket support"?

**Comment by ggtakec** [comment] 2019-03-30 07:43
We kept this issue open for a long time.
We will keep thinking about "less POSIX compliance but WORM Bucket support".
I will close this, but if the problem persists, please reopen or post a new issue.

**Closed by ggtakec** 2019-03-30 07:43 UTC

**Comment by evh69** [comment] 2019-04-15 15:54
@ggtakec we have application architecture that needs to support zero byte files and discovered this issue during testing.  I am sure this has been considered but will ask anyway ... Could a configuration switch that one could set that would allow a choice to create the initial file with some sort of filename pattern? we could leverage in the S3 Event Notification that we could use to ignore the initial file creation similar to an event filter?  

IE.  
1. Create initial file with [FILE_NAME] 'S3SF_TEMP' prefix, suffix, or file extension.
2. Implementors could create a S3 event filter to ignore the 'S3SF_TEMP' prefix, suffix, or file extension.
3. Open the file and write to the file.
4. Rename the file?

**Comment by mitexleo** [comment] 2024-12-18 12:34
Any workaround to avoid this issue?

**Comment by gaul** [comment] 2024-12-19 18:45
This issue was fixed years ago.  Please test with the latest version and open a new issue if you can reproduce the symptoms.

**Comment by mitexleo** [comment] 2024-12-20 00:38
I'm using the latest version available on Ubuntu APT Repository, a file is being uploaded twice.

**Comment by gaul** [comment] 2024-12-20 02:15
I'm locking this thread  Please open a new bug with debug logging.
