### ISSUE TITLE
Failed to access bucket

### ISSUE THREAD

**Issue by anaxmedia** [s3fs-fuse/s3fs-fuse#96] opened 2014-12-11 23:40 UTC
I'm receiving the below error when trying to connect to my bucket. I have permissions for my IAM credentials to access the bucket, I have the correct access key and IAM username setup in /etc/passwd-s3fs, any ideas? I'm on the latest version.

$ s3fs --version
Amazon Simple Storage Service File System V1.78 with OpenSSL
Copyright (C) 2010 Randy Rizun rrizun@gmail.com
License GPL2: GNU GPL version 2 http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ sudo s3fs -d -f [my bucket] /mnt/plex
    set_moutpoint_attribute(3379): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
s3fs_init(2650): init
s3fs_check_service(2968): check services.
    CheckBucket(2367): check a bucket.
    RequestPerform(1572): connecting to URL http://[my bucket].s3.amazonaws.com/
RequestPerform(1705): ### CURLE_HTTP_RETURNED_ERROR
RequestPerform(1710): HTTP response code =403
s3fs: Failed to access bucket.

**Comment by ggtakec** [comment] 2015-01-06 16:21
Hi,
Probably I think you should set ascesskey and secret in passed-s3fs, and specify iam_role="rolename" option.
Please try to do and reply if you do not solve this problem.

Thanks in advance.

**Comment by sawants** [comment] 2015-02-18 06:30
@ggtakec -

I am facing similar issue. I have a bucket created in our s3 storage account. I am trying to mount this on a centOS box. I have the "accessKeyId:secretAccessKey" set in s3fs password file. However when I try to mount a directory to this bucket using 

/usr/bin/s3fs -d -d bucket-name /location

I get the following error - 
FUSE library version: 2.8.3
nullpath_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56
INIT: 7.13
flags=0x0000b07b
max_readahead=0x00020000
s3fs: Failed to access bucket.

Any clues please.

NOTE - There were other suggestion to unmount / mount again. I tried that multiple times. However that didn't help. Also it doesn't seem to be any connectivity issue. I am able to get the file from the s3 storgae to this centOS box using aws s3 command and wget too without any issues.

**Comment by sawants** [comment] 2015-02-18 06:31
@anaxmedia - Can you please take a look at the earlier comment and see if you have any clues. How did you get around the issue you were facing.

**Comment by ggtakec** [comment] 2015-03-04 04:21
@sawants I'm sorry for replying late.

Maybe if your problem is caused by SignatureV4, you may be able to access by using the code of the master branch.
Since you can access to your bucket by wget, I think that your bucket is set to public(allow anywhere and everyone).
If it is set as public, you can be sure whichever this problem is authentication issues by invoking the s3fs with "public_bucket=1".
(If your bucket is nt set public, you will get "Operation not permitted" error after s3fs starts successful.)

Thanks in advance for your assistance.

**Comment by ggtakec** [comment] 2019-03-30 05:53
We kept this issue open for a long time.
I will close this, but if the problem persists, please reopen or post a new issue.

**Closed by ggtakec** 2019-03-30 05:53 UTC
