### ISSUE TITLE
Chown ownership issue: Input/output error

### ISSUE THREAD

**Issue by imtomjorge** [s3fs-fuse/s3fs-fuse#1560] opened 2021-02-09 16:42 UTC
#### Version of s3fs being used (s3fs --version)
V1.88 (commit:a4d916a)

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.9

#### Kernel information (uname -r)
5.4.0-1031-kvm

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
VERSION="20.04.2 LTS (Focal Fossa)"
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"

#### s3fs command line used, if applicable
```
chown backup1. /ftp2sis
```

#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
Feb  9 16:36:18 ftp2sis s3fs[786]: Loaded mime information from /etc/mime.types
Feb  9 16:36:18 ftp2sis s3fs[788]: init v1.88(commit:a4d916a) with OpenSSL
```
### Details about issue
I'm trying to build a Proxy between FTP/S3. I want to chown my mounted bucket for my specific FTP user called "backup1".
Here is the output:
```
chown: changing ownership of '/ftp2sis': Input/output error
```
Do you have any idea, what's going on? 
Thanks for your help

**Comment by gaul** [comment] 2021-02-09 23:10
Potential duplicate of #1547.  Could you try testing with the latest master?

**Comment by gaul** [comment] 2021-02-20 14:34
Please reopen if you can reproduce these symptoms with the latest master.

**Closed by gaul** 2021-02-20 14:34 UTC
Labels: needinfo
