### ISSUE TITLE
build instructions for osx?

### ISSUE THREAD

**Issue by rmoriz** [s3fs-fuse/s3fs-fuse#296] opened 2015-11-18 15:30 UTC
I'm getting the following error:

```shell

➜  s3fs-fuse git:(macosx) ✗ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
g++ -DHAVE_CONFIG_H -I. -I..  -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse -I/usr/include/libxml2    -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT s3fs.o -MD -MP -MF .deps/s3fs.Tpo -c -o s3fs.o s3fs.cpp
s3fs.cpp:30:10: fatal error: 'libxml/xpath.h' file not found
#include <libxml/xpath.h>
         ^
1 error generated.
make[2]: *** [s3fs.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

It would be awesome if you provide binary releases for homebrew-cask (like osxfuse, sshfs).

**Comment by MBuffenoir** [comment] 2016-04-14 13:39
Got the same error here, tried to brew install libxml2 without success ...

**Comment by ggtakec** [comment] 2016-04-17 12:55
@MBuffenoir @rmoriz I'm sorry for late reply.
It is not clear because it does not reproduce, but maybe you should update xcode.
For example, "xcode-select --install".

Please check your system and try it if you can.
Regards,

**Comment by pakshi** [comment] 2016-07-12 20:47
Running this "xcode-select --install", got me past the "libxml/xpath.h" error.
Thanks ggt

**Comment by ggtakec** [comment] 2016-07-24 07:40
@pakshi Thanks for your reply.
It seems that this problem is resolved, so I'm closing this issue.
But if you continue to have this isue, please reopen this.
Thanks for your help.

**Closed by ggtakec** 2016-07-24 07:40 UTC
