### ISSUE TITLE
segfault mounting through /etc/fstab

### ISSUE THREAD

**Issue by sbonasu** [s3fs-fuse/s3fs-fuse#1164] opened 2019-10-01 17:16 UTC
#### Version of s3fs being used (s3fs --version)
s3fs --version
Amazon Simple Storage Service File System V1.85 (commit:1db94a0) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Name        : fuse
Version     : 2.9.2
Release     : 11.el7
Architecture: x86_64
Install Date: Fri 27 Sep 2019 11:30:35 PM UTC
Group       : System Environment/Base
Size        : 223297
License     : GPL+
Signature   : RSA/SHA256, Mon 06 Aug 2018 01:13:08 PM UTC, Key ID 199e2f91fd431d51
Source RPM  : fuse-2.9.2-11.el7.src.rpm
Build Date  : Tue 24 Jul 2018 02:58:28 PM UTC
Build Host  : x86-039.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://github.com/libfuse/libfuse
Summary     : File System in Userspace (FUSE) utilities

#### Kernel information (uname -r)
3.10.0-1062.1.2.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)

#### s3fs command line used, if applicable
works fine
s3fs bucketname /directory -o iam_role="auto" -o url="https://s3-us-east-2.amazonaws.com" -o endpoint=us-east-2 -o dbglevel=info -o curldbg -o allow_other -o use_cache=/tmp

#### /etc/fstab entry, if applicable
s3fs#bucketname /directory fuse fuse _netdev,iam_role=auto,rw,nosuid,nodev,allow_other,nonempty,endpoint=us-east-2,url=http://s3-us-east-2.amazonaws.com 0 0

Doesn't work
s3fs: unable to access MOUNTPOINT xxx: Transport endpoint is not connected

#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
s3fs.cpp:set_s3fs_log_level(297): change debug level from [CRT] to [INF]
   PROC(uid=0, gid=0) - MountPoint(uid=1756527704, gid=1756527704, mode=40750)
init v1.85(commit:1db94a0) with OpenSSL
check services.
     [IAM role="auto"]
curl.cpp:ResetHandle(2039): The CURLOPT_SSL_ENABLE_ALPN option could not be unset. S3 server does not support ALPN, then this option should be disabled to maximize performance. you need to use libcurl 7.36.0 or later.
curl.cpp:ResetHandle(2042): The S3FS_CURLOPT_KEEP_SENDING_ON_ERROR option could not be set. For maximize performance you need to enable this option and you should use libcurl 7.51.0 or later.
s3fs[17681]: Pool empty: force to create new handler
kernel: s3fs[17682]: segfault at 7f25fa988ff0 ip 00007f25ff024ec6 sp 00007f25fa988ff0 error 6 in libc-2.17.so[7f25fefa8000+1c3000]

### Details about issue

Hi,

mounting through /etc.fstab giving segfault error. 
same settings work in v1.85 commit:81102a5
s3fs --version
Amazon Simple Storage Service File System V1.85 (commit:81102a5) with OpenSSL

**Comment by MattFenelon** [comment] 2019-10-02 11:05
I think I'm seeing the same issue. The issue started happening since this commit - https://github.com/s3fs-fuse/s3fs-fuse/commit/58b3cce3207576150e7285148bb623c92caf8db3. The commit before (https://github.com/s3fs-fuse/s3fs-fuse/commit/81102a59637ff75ecf139bc977759188c566e280) works as expected.

#### Version of s3fs being used (s3fs --version)
`Amazon Simple Storage Service File System V1.85 (commit:461a346) with OpenSSL`

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
`2.9.2`

```
Package: fuse
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 152
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.9.2-4ubuntu4.14.04.1
Depends: libc6 (>= 2.14), libfuse2 (= 2.9.2-4ubuntu4.14.04.1), adduser, mount (>= 2.19.1), sed (>= 4), udev | makedev
Conffiles:
 /etc/fuse.conf 298587592c8444196833f317def414f2
```

#### Kernel information (uname -r)
`3.13.0-170-generic`

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
```
NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.6 LTS"
VERSION_ID="14.04"
```

#### s3fs command line used, if applicable

```
s3fs REDACTED:/REDACTED /var/sftp/REDACTED/ -d -d -f -o f2 -o curldbg,url=https://s3.amazonaws.com,iam_role=REDACTED,use_sse,allow_other,mp_umask=0077,enable_content_md5,retries=10,enable_noobj_cache,stat_cache_expire=600,uid=$(id -u REDACTED),gid=$(id -g REDACTED)
```

#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)

```
Oct  2 10:55:07 ip-172-31-38-218 s3fs[8008]: Pool empty: force to create new handler
Oct  2 10:55:07 ip-172-31-38-218 s3fs[8008]:       [IAM role=REDACTED]
Oct  2 10:55:07 ip-172-31-38-218 s3fs[8008]: Pool empty: force to create new handler
Oct  2 10:55:07 ip-172-31-38-218 kernel: [ 6195.999227] s3fs[8009]: segfault at 7ff8acab0f28 ip 00007ff8b1fa1ccd sp 00007ff8acab0f30 error 6 in libc-2.19.so[7ff8b1f58000+1be000]
```
### Details about issue

```shell
FUSE library version: 2.9.2
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.22
flags=0x0000f7fb
max_readahead=0x00020000
[CRT] s3fs.cpp:set_s3fs_log_level(297): change debug level from [CRT] to [INF]
[CRT] s3fs.cpp:set_s3fs_log_level(297): change debug level from [INF] to [DBG]
[INF]     s3fs.cpp:set_mountpoint_attribute(4382): PROC(uid=0, gid=0) - MountPoint(uid=1000, gid=1000, mode=40700)
[INF] s3fs.cpp:s3fs_init(3474): init v1.85(commit:461a346) with OpenSSL
[INF] s3fs.cpp:s3fs_check_service(3809): check services.
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 31
[WAN] curl.cpp:ResetHandle(1880): The CURLOPT_SSL_ENABLE_ALPN option could not be unset. S3 server does not support ALPN, then this option should be disabled to maximize performance. you need to use libcurl 7.36.0 or later.
[WAN] curl.cpp:ResetHandle(1883): The S3FS_CURLOPT_KEEP_SENDING_ON_ERROR option could not be set. For maximize performance you need to enable this option and you should use libcurl 7.51.0 or later.
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 30
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 29
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 28
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 27
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 26
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 25
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 24
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 23
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 22
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 21
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 20
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 19
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 18
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 17
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 16
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 15
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 14
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 13
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 12
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 11
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 10
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 9
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 8
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 7
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 6
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 5
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 4
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 3
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 2
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 1
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[DBG] curl.cpp:GetHandler(288): Get handler from pool: rest = 0
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[INF] curl.cpp:GetHandler(295): Pool empty: force to create new handler
[DBG] curl.cpp:RequestPerform(2220): connecting to URL http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACATED
[INF]       curl.cpp:GetIAMCredentials(2691): [IAM role=REDACATED]
[INF] curl.cpp:GetHandler(295): Pool empty: force to create new handler

...

Segmentation fault (core dumped)
```

**Comment by MattFenelon** [comment] 2019-10-07 08:42
Possible duplicate of https://github.com/s3fs-fuse/s3fs-fuse/issues/1162.

**Comment by gaul** [comment] 2019-10-24 22:34
Could you run this under gdb and share the backtrace of the SIGABRT? Alternatively Valgrind should show the same thing.

**Comment by gaul** [comment] 2020-02-03 08:10
Closing due to inactivity.  Please reopen if symptoms persist.

**Closed by gaul** 2020-02-03 08:10 UTC
