### ISSUE TITLE
Build error against >=libxml2-2.12 - s3fs.cpp:3492:27: error: xmlReadMemory was not declared in this scope; did you mean xmlInitMemory?

### ISSUE THREAD

**Issue by a17r** [s3fs-fuse/s3fs-fuse#2405] opened 2024-01-31 09:47 UTC
Downstream report: https://bugs.gentoo.org/917522

Probably just a missing header - to quote libxml2 upstream changelog:

> Several cyclic dependencies in public header files were fixed. As a result, certain headers won’t include other headers as before.

#### Version of s3fs being used (`s3fs --version`)
1.93

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)
Gentoo

**Comment by ggtakec** [comment] 2024-02-04 05:07
It appears that 2.12 is not yet officially supported by any distribution other than Gentoo. And I haven't been able to confirm it directly yet.

Is it possible for you to confirm the following?
- Is the libxml2-dev package installed?
- Would the compilation be successful if you add `#include <libxml/parser.h>` to `src/s3fs_xml.h`?

Thanks in advance for your assistance.

**Comment by gaul** [comment] 2024-02-13 23:10
I tested this on Fedora 40 with libxml2-devel-2.12.5-1.fc40.x86_64 but could not reproduce these symptoms.

**Comment by a17r** [comment] 2024-02-14 09:07
The downstream bug was filed with `2.12.0`, the circular dependency was readded to upstream headers for `2.12.3`, that's why you can't reproduce it:

https://gitlab.gnome.org/GNOME/libxml2/-/commit/72007096e2812f80c9bce2485d85e6d13bb7dbb5

@ggtakec Gentoo is source-based so there are no separate -dev packages. Downstream build.log confirms successful libxml2 detection anyway. ;)

**Comment by a17r** [comment] 2024-02-14 09:16
> * Would the compilation be successful if you add `#include <libxml/parser.h>` to `src/s3fs_xml.h`?

Yes it fixes compilation. :)

**Comment by ggtakec** [comment] 2024-02-19 11:38
@a17r Thanks for your help.
To be clear, is this issue resolved in versions 2.12.3 and later?

@gaul
Even if I write to include `libxml/parser.h` directly in `s3fs_xml.h`, it will not cause any problems when using versions other than `2.12.0`, but should I PR this and merge it?
It may seem like a special case, but by adding it you can avoid problems with specific versions. (Although it is a waste of description, I think it is okay to write it.)
If this should be added, I can create a PR for this.

**Comment by a17r** [comment] 2024-02-22 09:37
@ggtakec thanks for making the PR. It is not so much that Gentoo needs it, rather that sources should include what they use, if in the future libxml2 will finally get rid of this then s3fs-fuse will no longer be affected.

**Comment by ggtakec** [comment] 2024-02-23 01:59
@a17r Excuse me, but let me confirm that I haven't misunderstood yet.
Does this mean that in the combination of Gentoo+libxml (2.12), there are still issues that are required in addition to the code merged by PR?

**Comment by a17r** [comment] 2024-02-23 12:35
No, your PR perfectly solves the issue, I was just alluding to the commit message mentioning Gentoo, when it is not really distro specific (at the time of solving the PR already >=2.12.4 was available).

**Closed** 2024-02-23 14:40 UTC
