### ISSUE TITLE
Random write behavior

### ISSUE THREAD

**Issue by kunallillaney** [s3fs-fuse/s3fs-fuse#808] opened 2018-08-08 19:25 UTC
I had a few questions on how s3fs handles random writes since I seeing some weird network stats (given the disclaimer in the README and this subsequent post #607)

Background:
* Setup: Existing file on S3 - 100MB. I am using fio for random writes on this and monitoring the network I/O using slurm.
* From my understanding, S3FS prefetches data in 40MB (multipart block size* threads) blocks into the cache when a region is a read. This is verified by slurm and the sparse file in the cache.
* However, when I perform random writes on S3FS, say changing a single byte, no data is fetched either into the cache or shown by slurm (double checked with /proc/net/dev/) but file size worth of data (100MB in this case) does get transmitted to S3. Here s3fs is not overwriting the other parts of the file with garbage data but correctly updating the single byte.

Question:
* In the random write case, my assumption was s3fs did a multipart-download, merge changes and multipart-upload. Is this not the case? Does it perform multipart-copy for unchanged regions for S3 (similar to the operation for rename) but the network stats do not support this since it should have only transmitted 40MB worth data and copied the other 60MB. Am I missing something?

Thanks.

**Comment by kunallillaney** [comment] 2018-08-08 19:29
And a follow on question is if does it indeed use multi-part copy, then how does it get around the [5GB target file size limit](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPartCopy.html) for range reads placed by S3.

**Comment by gaul** [comment] 2018-09-11 06:01
Which options do you mount s3fs with?  Have you enabled the data cache?  This could explain the read behavior you experience.

For writes, s3fs does issue multipart uploads and copies data for the unchanged regions.  Hence you should expect a 1-byte update to a 100 MB file to copy (9) 10 MB chunks and upload a whole 10 MB chunk.  If the cache does not contain this range it will have to download it before uploading the whole part.

**Comment by kunallillaney** [comment] 2018-09-11 06:08
The data cache is enabled. I tried this by opening the file in "r+" mode to update. In this case, the file ends up with correct data in the updated region and zeros everywhere else (which sounds like a bug to me). I don't think s3fs copies data for the other 9 chunks. If it does, can you please explain how it gets around the 5GB file size limit I mention above? S3FS needs to do range reads on the remaining 90MB of data to do so but S3 does not allow it since the target file is only 100MB.
I believe this was verified by @orozery as well.

**Comment by gaul** [comment] 2018-09-11 06:13
If you observe data corruption, with unexpected zeros, this is a serious issue and I will take a look at it.  Can you minimize a test case with exact steps to reproduce this behavior?

s3fs should copy ranges which are not updated on the server.  S3 parts, either uploaded or copied, are limited to >= 5 MB and <= 5 GB but the total MPU object size can be up to 5 TB.

**Comment by gaul** [comment] 2018-09-17 20:34
The boto3 documentation for part size is incorrect.  This phrase seems to originate from some AWS code generation which I cannot find the source for so I opened aws/aws-cli#3577 which has the same issue and hope they can direct to the proper location.

Did you reproduce your data loss issue?  Please provide instructions so I can investigate this otherwise can you close the issue?

**Comment by kunallillaney** [comment] 2018-09-17 23:08
@gaul Sorry I have been busy with a paper have been unable to look at this. When I had looked at it last, I was able to reproduce it multiple times and the issue was also confirmed by another contributor to the repository (mentioned above). I am positive that this issue exists and I will post the steps sometime next week.

**Comment by kunallillaney** [comment] 2018-10-31 15:28
@gaul Sorry I was busy with a paper and then traveling for a conference. Here are the steps to reproduce this bug

1. Mount s3fs with cache enabled option.
2. Copy a file greater than number of threadsxmultipart size. I chose a file of about 200MB for a 4 thread 10 MB part size setup. Please do no create this file via dd since this creates a file filled with \x00.
3. Unmount s3fs and clear the cache.
4. Mount s3fs again with the same options as before.
5. Open the file from C or python with r+ mode. (I checked this with both these languages and the issue occurs in both.) 
6. Write to the file at the start or some offset and close the file.
7. Read the file again and check at offsets which are not the offset yo wrote to and you see \x00.
8. Alternately, you can unmount the filesystem clear the cache and then repeat Step 6 and the same issue occurs.

Please let me know if this is unclear or you have further questions.

**Comment by gaul** [comment] 2019-01-23 17:27
@kunallillaney Could you test again with master?  We fixed a few zero data issues and #918 is the most similar to your symptom.

**Comment by gaul** [comment] 2019-06-25 20:29
Closing due to inactivity.

**Closed by gaul** 2019-06-25 20:29 UTC
