### ISSUE TITLE
Not able to find _clock_gettime symbol while mounting s3 bucket

### ISSUE THREAD

**Issue by ssahu** [s3fs-fuse/s3fs-fuse#468] opened 2016-09-16 00:36 UTC
```
[INF]       curl.cpp:insertV4Headers(2237): computing signature [HEAD] [/.DS_Store] [] []
[INF]       curl.cpp:url_to_host(100): url is http://s3.amazonaws.com
[INF]       curl.cpp:RequestPerform(1910): HTTP response code 200
[INF]       cache.cpp:AddStat(346): add stat cache entry[path=/.DS_Store]
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/bin/s3fs
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/bin/s3fs
  Expected in: /usr/lib/libSystem.B.dylib
```

Anyone got this issue on trying to mount the s3 bucket like below?
`s3fs -f -d s3_sync local_folder -o passwd_file=.passwd-s3fs`

I upgraded to Xcode 8 yesterday, maybe that caused it?

**Comment by ggtakec** [comment] 2016-09-19 06:25
@ssahu 
Do you use latest codes in master(or macosx) branch?
Latest codes check clock_gettime function at configure and prepare an alternative function.
https://github.com/s3fs-fuse/s3fs-fuse/blob/macosx/src/cache.cpp#L59-L70

Please check you code base and try to rebuld all(start to run autogen.sh).

Thanks in advance for your assistance.

**Comment by jbarlow83** [comment] 2016-11-23 06:38
Same error here. macOS 10.11.6, Xcode 8.1, v1.80 

The homebrew script runs `./autogen.sh` and builds v1.80 from source, but this error still occurs.

HEAD version fails with the same error.

**Comment by jbarlow83** [comment] 2016-11-23 06:46
Compiled HEAD from source and it built a working version, so it seems like the problem is in the Homebrew script.

**Comment by jbarlow83** [comment] 2016-12-02 00:15
cache.cpp somehow is expecting clock_gettime to be an external symbol so it overlooks the static local copy provided in the macos case.

See the homebrew issue where renaming clock_gettime in that module is sufficient to fix. (This would break non-macOS however).

**Comment by ggtakec** [comment] 2016-12-04 10:49
@jbarlow83 I'm sorry for my late reply.
I changed clock_gettime function name for not conflicting same function in library.
I merged codes to master and macosx branches, please try to use it.
Thanks very much for your help.

**Closed by ggtakec** 2016-12-04 10:49 UTC
