### ISSUE TITLE
Mount hangs following upgrade to 1.80

### ISSUE THREAD

**Issue by makered** [s3fs-fuse/s3fs-fuse#429] opened 2016-06-06 17:27 UTC
I recently upgraded from v1.79 to v1.80. At first everything seemed to go well and I was able to access S3 via the mount.

After some time, however, any attempt to access the S3 mount or running disk-related commands (e.g. `df -h`) would cause the request to hang until the system was rebooted. The log does not seem to reveal anything suspicious. 

The mount definition in /etc/fstab is:

`s3fs#mybucketname /s3 fuse use_cache=/cache,url=http://s3.amazonaws.com,enable_noobj_cache,enable_content_md5,stat_cache_expire=30,nonempty,allow_other,_netdev,default_permissions,iam_role=MYROLE,parallel_count=10,uid=1004,gid=1001,umask=0002,nodev,noauto 0 0`

Is there anything more specific I can do to troubleshoot?

Thank you

**Comment by ggtakec** [comment] 2016-06-12 02:14
Hi, @makered 
If you can reproduce, please try to run with the dbglevel options(and curldbg).
I think that it is possible to obtain a detailed debugging information.
However, because the log file will be very large size by these options, please use with caution.

Thanks in advance for your help.

**Comment by ggtakec** [comment] 2019-03-30 07:49
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.

**Closed by ggtakec** 2019-03-30 07:49 UTC
