### ISSUE TITLE
s3fs writes failing on retention enabled vaults on IBM Cloud object storage

### ISSUE THREAD

**Issue by SurjyaHaz** [s3fs-fuse/s3fs-fuse#862] opened 2018-11-22 05:46 UTC
Version of s3fs being used (s3fs --version)
1.84

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse
Version     : 2.9.2
Release     : 11.el7
Architecture: x86_64
Install Date: Wed 21 Nov 2018 12:40:12 AM EST
Group       : System Environment/Base
Size        : 223297
License     : GPL+

#### Kernel information (uname -r)
3.10.0-957.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"

#### s3fs command line used, if applicable
s3fs -o passwd_file=*** BucketVault /myfolder -o use_path_request_style -o url=https://<IPAddress> -o allow_other -f -o curldbg

### Details about issue
I am able to mount the IBM Cloud Object Storage bucket named "BucketVault" using s3fs. However if I enable retention on the bucket on the COS side, the write fails(cp /tmp/t1 to /COSMount).  Retention will not allow any modification to an S3 object once it gets created. On trying to copy, s3fs first creates a 0kb file with a 1st PUT api and then issues another PUT which fails because the object storage does not allow to modify the file. If retention is disabled, the writes go through fine. My question is are there any plans to modify s3fs to make writes possible with retention turned on (like do the write with one PUT call) so that the retention feature can be availed.?

**Comment by SurjyaHaz** [comment] 2018-12-03 13:15
Any update on this please?

**Comment by gaul** [comment] 2020-06-23 03:18
Duplicate of #1013 which has more context.

**Closed by gaul** 2020-06-23 03:18 UTC
