### ISSUE TITLE
Does s3fs limit the size of uploaded files?

### ISSUE THREAD

**Issue by XiaoGe2030** [s3fs-fuse/s3fs-fuse#1060] opened 2019-06-30 08:04 UTC
Does s3fs limit the size of uploaded files? Or ,There is some params limit the size ?
I upload a 10G file was successful, but uploading a 100G file failed. please help me, and tell me why,Thanks!!!
![image](https://user-images.githubusercontent.com/22184388/60394043-90c48d00-9b50-11e9-8df2-79d1aff4e79e.png)

![image](https://user-images.githubusercontent.com/22184388/60394053-b6ea2d00-9b50-11e9-9819-55504b1e9074.png)

**Comment by threadfly** [comment] 2019-07-02 03:08
Hello, why is your test speed up to 310MB/s?

**Comment by jheiselman** [comment] 2019-07-02 13:56
According to the FAQ, the size is dependent on the S3 service you are using and isn't limited by the driver.
https://github.com/s3fs-fuse/s3fs-fuse/wiki/Fuse-Over-Amazon#overview

**Comment by gaul** [comment] 2019-07-02 16:42
I suspect that this is a duplicate of as #1019.  Could you run s3fs with `-f -d -o curldbg` to check?  If so, please downgrade to version 1.84 until we can address this properly.

**Comment by gaul** [comment] 2020-06-23 02:26
Closing due to inactivity.  Please reopen if symptoms persist.

**Closed by gaul** 2020-06-23 02:26 UTC
Labels: needinfo
