### ISSUE TITLE
s3fs_check_service(3806): invalid credentials - result of checking service

### ISSUE THREAD

**Issue by fcapurro** [s3fs-fuse/s3fs-fuse#475] opened 2016-09-23 16:09 UTC
Hello

I been trying to get s3fs to work, i tried it on a server and my desktop and I keep getting the same error either way, saying my credentials file is not valid, however I use the exactly same id:key in awscli and it works there

MS-7788 s3fs-fuse # s3fs s3://my-test-bucket  /aws -o passwd_file=/etc/passwd-s3fs -f
[CRT] s3fs.cpp:s3fs_init(3371): init v1.80(commit:9f174d7) with OpenSSL
[CRT] s3fs.cpp:s3fs_check_service(3806): invalid credentials - result of checking service.

MS-7788 s3fs-fuse # cat /etc/passwd-s3fs
My_aws_access_key_XXXX:My_Aws_Secret_access_key_YYYY
7788 s3fs-fuse # 

MS-7788 s3fs-fuse # aws configure
AWS Access Key ID [---------------XXXX]:  <--- same value as in first part of /etc/passwd-s3fs
AWS Secret Access Key [----------------YYYY]: <-- same value as second part after ":"

MS-7788 s3fs-fuse # aws s3 ls
2010-10-25 13:08:47 my-test-bucket

this is driving me crazy, what could the the issue? I'm using a valid access ID and KEY

thx

**Comment by ggtakec** [comment] 2016-10-02 06:49
@fcapurro 
[CRT] s3fs.cpp:s3fs_check_service(3806): invalid credentials - result of checking service.

It is put when s3fs can not access the bucket for checkcing.
I think your credential was not wrong, but something error was received from S3.

If you can, please run s3fs with "-o dbglevel=info" and "-o curldbg".
Thus we can get detail reason for this error, and it helps us to solve this issue.

And please let us know about your command option for s3fs.

Thanks in advance for your help.

**Comment by jcomeauictx** [comment] 2017-01-29 21:13
the problem is you're using `s3://` in front of the bucketname. I know because I just made the same error. just use the bucketname with no prefix and it should work.

**Comment by jcomeauictx** [comment] 2017-01-29 21:14
note to s3fs developers: returning the `-EPERM` back to the shell would be nice. silent failures are the worst.

**Comment by ggtakec** [comment] 2017-05-05 20:18
@jcomeauictx I'm sorry for my late reply.
Since the format specifying the bucket name and path is "bucket[:/path]", it was an error at the stage of connection to the bucket, not at the stage of parameter check.
Thus, I think that the error message was only put in /var/syslog etc, and user could not know the details of the error.
So, I merged new codes(#580) that is that s3fs checks this wrong parameter at the stage of parameter check, and s3fs will decide that ": //" string in parameter is error.

Thank you very much!
I'm closing this issue, but if you have more, please reopen this issue.

**Closed by ggtakec** 2017-05-05 20:18 UTC
