### ISSUE TITLE
errors when mounting emc ecs bucket

### ISSUE THREAD

**Issue by bennypi** [s3fs-fuse/s3fs-fuse#393] opened 2016-04-12 10:45 UTC
Hi folks, 
I've deployed an emc ecs instance, see https://github.com/EMCECS/ECS-CommunityEdition.
I've created several buckets, which are accessible with the cloudberry explorer.
I try to mount one of these buckets with s3fs, but I keep getting errors and I can't list the items in the mountfolder.
The command i use is:
`sudo s3fs -o url=http://vtf-emc-ecs-node1.tf.company-name-test.de -o allow_other -o no_check_certificate  worm-bucket ~/worm-bucket -d -d -f -o f2 -o c urldbg -o uid=1000 -o gid=1000`
I've attached the output from the previous command:
[s3fs-error.txt](https://github.com/s3fs-fuse/s3fs-fuse/files/214805/s3fs-error.txt)
In a second shell I try to list the files in that bucket, which is not working:
username@vtf-govlza04:~$ ll worm-bucket/
ls: lese Verzeichnis worm-bucket/: Die Operation ist nicht erlaubt
insgesamt 0

Do you have any ideas how to solve this?
Thanks.

**Comment by victorock** [comment] 2016-04-26 08:43
Benny,
Do you have any Loadbalance in front of your ECS answering on default HTTP/HTTPS ports?
If it's not the case, for S3 API access, you should specify the port 9020 (HTTP) or 9021 (HTTPS).
Also from the logs, it seems that S3FS prepend bucket name, so make sure that the entry is properly created in your DNS, and ECS is configured to respond to this FQDN (Settings->Object Base URL).
Please refer to the following documentations that explains how to access S3 API on ECS:
http://www.emc.com/techpubs/ecs/ecs_s3_supported_features-1.htm
https://www.emc.com/techpubs/ecs/ecs_use_s3_apps_with-1.htm

Sincerely,
Victor da Costa

**Comment by ggtakec** [comment] 2016-05-14 10:33
@bennypi I'm sorry for my late reply.

I chcked and found the following lines from your log, which lines indicate the cause of this problem.
```
[INF]       curl.cpp:RequestPerform(1754): HTTP response code 200
:1: parser error : StartTag: invalid element name
<!doctype html>
 ^
:1: parser error : Extra content at the end of the document
<!doctype html>
 ^
[ERR] s3fs.cpp:list_bucket(2474): xmlReadMemory returns with error.

```
This indicates that an error has occurred at the time to parse the results of list object request.
( GET /?delimiter=/&max-keys=1000&prefix= HTTP/1.1 )

In other words, it seems that it has returned diffrent S3 XML format.

I am not familiar with ECS, I do not know this cause.
However, this cause might about loadbalancer which is designated by the @victorock, so you should also check it.
I know only that s3fs has received a list object's format do not expect of s3fs.

Regards,

**Comment by ggtakec** [comment] 2019-03-30 07:30
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.

**Closed by ggtakec** 2019-03-30 07:30 UTC
Labels: question
