### ISSUE TITLE
cannot mount S3 bucket on RHEL 6.7

### ISSUE THREAD

**Issue by kaushalender** [s3fs-fuse/s3fs-fuse#889] opened 2019-01-11 07:36 UTC
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
_example: 1.00_

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_

#### Kernel information (uname -r)
_command result: uname -r_

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```

**Comment by kaushalender** [comment] 2019-01-11 07:38
Hi,

I have installed s3-fs on rhel 6.7 if i am trying to mount s3fs  following is hapening

[root@ip-192-168-5-8 /]# s3fs bucket[:/vas-app-logs] /app-logs -o passwd_file=/etc/passwd-s3fs -o use_path_request_style -o -d -d -f
[CRT] s3fs.cpp:set_s3fs_log_level(275): change debug level from [CRT] to [INF]
[INF]     s3fs.cpp:set_mountpoint_attribute(4252): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40777)

**Comment by kaushalender** [comment] 2019-01-11 07:48
Version of s3fs being used (s3fs --version)

s3fs --version
Amazon Simple Storage Service File System V1.84(commit:e8033f9) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Version of fuse being used 

pkg-config --modversion fuse
2.9.4

Kernel information 

 uname -r
2.6.32-754.3.5.el6.x86_64

cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)

s3fs command line used, if applicable
[root@ip-192-168-5-8 /]# s3fs bucket[:/vas-app-logs] /app-logs -o passwd_file=/etc/passwd-s3fs -o use_path_request_style -o -d -d -f


/var/log/messages


Jan 11 01:41:39 ip-192-168-5-8 s3fs[19898]: s3fs.cpp:set_s3fs_log_level(275): change debug level from [CRT] to [DBG]
Jan 11 01:41:39 ip-192-168-5-8 s3fs[19898]:     PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40777)
Jan 11 01:41:39 ip-192-168-5-8 s3fs[19898]: s3fs.cpp:set_s3fs_log_level(275): change debug level from [CRT] to [DBG]
Jan 11 01:41:39 ip-192-168-5-8 s3fs[19898]:     PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40777)
Jan 11 01:41:39 ip-192-168-5-8 s3fs[19898]: s3fs.cpp:set_s3fs_log_level(275): change debug level from [CRT] to [DBG]
Jan 11 01:41:39 ip-192-168-5-8 s3fs[19898]:     PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40777)

**Comment by gaul** [comment] 2019-02-02 03:01
Duplicate of #907?

**Closed** 2019-06-25 20:26 UTC
