### ISSUE TITLE
Random dismount on S3

### ISSUE THREAD

**Issue by drsku** [s3fs-fuse/s3fs-fuse#210] opened 2015-07-17 09:09 UTC
Our S3 bucket mounted on EC2 randomly dismounted on our first day of going live on AWS. We weren't doing anything special as far as we know. Our web site therefore went down... bit of downer.

Anyone got any suggestions to avoid this happening in the future, or know any common causes of this behaviour.

Thanks
Dan

**Comment by ggtakec** [comment] 2016-01-17 10:53
I'm sorry for that this issue had been left at a long period of time.

Could you run s3fs with dbglevel(and curldbg if you need)?
This option let s3fs put debug log into syslog(or displaying messages), thus the log helps us to solve this issue.

Thanks in advance for your assistance.

**Comment by pete-robinson** [comment] 2017-03-29 09:31
Hi @ggtakec,
We are experiencing this issue too. This happens completely at random with seemingly no trigger. When trying to LS the directory, the error we get when this happens is 'Transport endpoint not connected'.

The s3fs instance is mounted with:
sudo s3fs -o allow_other {bucket-name} {destination-directory}

As far as I'm aware, s3fs isn't producing any log files - is there a way to enable logging?

Regards
Pete

**Comment by andrewgaul** [comment] 2017-03-29 18:23
@pete-robinson Run s3fs with `-f -d` (foreground, debug).

**Comment by ggtakec** [comment] 2017-04-09 06:57
@drsku @pete-robinson 
When this problem occurs, is the s3fs process abnormally terminated?
If it ends abnormally, I think that we can identify the cause early if you know the status of the stack from the core file at that time.
And if you can, please try to use latest codes in master branch.

Thanks in advance for your help.

**Comment by ggtakec** [comment] 2019-03-30 06:34
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.

**Closed by ggtakec** 2019-03-30 06:34 UTC
